// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: output.proto

package guru.bonacci.reactive.kafka;

public final class ProtoOutput {
  private ProtoOutput() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Output)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required string foo = 2;</code>
     * @return Whether the foo field is set.
     */
    boolean hasFoo();
    /**
     * <code>required string foo = 2;</code>
     * @return The foo.
     */
    java.lang.String getFoo();
    /**
     * <code>required string foo = 2;</code>
     * @return The bytes for foo.
     */
    com.google.protobuf.ByteString
        getFooBytes();

    /**
     * <code>required int32 goo = 3;</code>
     * @return Whether the goo field is set.
     */
    boolean hasGoo();
    /**
     * <code>required int32 goo = 3;</code>
     * @return The goo.
     */
    int getGoo();

    /**
     * <code>required double bar = 4;</code>
     * @return Whether the bar field is set.
     */
    boolean hasBar();
    /**
     * <code>required double bar = 4;</code>
     * @return The bar.
     */
    double getBar();

    /**
     * <code>required bool baz = 5;</code>
     * @return Whether the baz field is set.
     */
    boolean hasBaz();
    /**
     * <code>required bool baz = 5;</code>
     * @return The baz.
     */
    boolean getBaz();
  }
  /**
   * Protobuf type {@code protobuf.Output}
   */
  public static final class Output extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Output)
      OutputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Output.newBuilder() to construct.
    private Output(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Output() {
      id_ = "";
      foo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Output();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return guru.bonacci.reactive.kafka.ProtoOutput.internal_static_protobuf_Output_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return guru.bonacci.reactive.kafka.ProtoOutput.internal_static_protobuf_Output_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              guru.bonacci.reactive.kafka.ProtoOutput.Output.class, guru.bonacci.reactive.kafka.ProtoOutput.Output.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>required string id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FOO_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object foo_ = "";
    /**
     * <code>required string foo = 2;</code>
     * @return Whether the foo field is set.
     */
    @java.lang.Override
    public boolean hasFoo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string foo = 2;</code>
     * @return The foo.
     */
    @java.lang.Override
    public java.lang.String getFoo() {
      java.lang.Object ref = foo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          foo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string foo = 2;</code>
     * @return The bytes for foo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFooBytes() {
      java.lang.Object ref = foo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        foo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GOO_FIELD_NUMBER = 3;
    private int goo_ = 0;
    /**
     * <code>required int32 goo = 3;</code>
     * @return Whether the goo field is set.
     */
    @java.lang.Override
    public boolean hasGoo() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 goo = 3;</code>
     * @return The goo.
     */
    @java.lang.Override
    public int getGoo() {
      return goo_;
    }

    public static final int BAR_FIELD_NUMBER = 4;
    private double bar_ = 0D;
    /**
     * <code>required double bar = 4;</code>
     * @return Whether the bar field is set.
     */
    @java.lang.Override
    public boolean hasBar() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required double bar = 4;</code>
     * @return The bar.
     */
    @java.lang.Override
    public double getBar() {
      return bar_;
    }

    public static final int BAZ_FIELD_NUMBER = 5;
    private boolean baz_ = false;
    /**
     * <code>required bool baz = 5;</code>
     * @return Whether the baz field is set.
     */
    @java.lang.Override
    public boolean hasBaz() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required bool baz = 5;</code>
     * @return The baz.
     */
    @java.lang.Override
    public boolean getBaz() {
      return baz_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFoo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGoo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBar()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBaz()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, foo_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, goo_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeDouble(4, bar_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBool(5, baz_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, foo_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, goo_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, bar_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, baz_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof guru.bonacci.reactive.kafka.ProtoOutput.Output)) {
        return super.equals(obj);
      }
      guru.bonacci.reactive.kafka.ProtoOutput.Output other = (guru.bonacci.reactive.kafka.ProtoOutput.Output) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (!getId()
            .equals(other.getId())) return false;
      }
      if (hasFoo() != other.hasFoo()) return false;
      if (hasFoo()) {
        if (!getFoo()
            .equals(other.getFoo())) return false;
      }
      if (hasGoo() != other.hasGoo()) return false;
      if (hasGoo()) {
        if (getGoo()
            != other.getGoo()) return false;
      }
      if (hasBar() != other.hasBar()) return false;
      if (hasBar()) {
        if (java.lang.Double.doubleToLongBits(getBar())
            != java.lang.Double.doubleToLongBits(
                other.getBar())) return false;
      }
      if (hasBaz() != other.hasBaz()) return false;
      if (hasBaz()) {
        if (getBaz()
            != other.getBaz()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasFoo()) {
        hash = (37 * hash) + FOO_FIELD_NUMBER;
        hash = (53 * hash) + getFoo().hashCode();
      }
      if (hasGoo()) {
        hash = (37 * hash) + GOO_FIELD_NUMBER;
        hash = (53 * hash) + getGoo();
      }
      if (hasBar()) {
        hash = (37 * hash) + BAR_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getBar()));
      }
      if (hasBaz()) {
        hash = (37 * hash) + BAZ_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getBaz());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static guru.bonacci.reactive.kafka.ProtoOutput.Output parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static guru.bonacci.reactive.kafka.ProtoOutput.Output parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static guru.bonacci.reactive.kafka.ProtoOutput.Output parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static guru.bonacci.reactive.kafka.ProtoOutput.Output parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static guru.bonacci.reactive.kafka.ProtoOutput.Output parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static guru.bonacci.reactive.kafka.ProtoOutput.Output parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static guru.bonacci.reactive.kafka.ProtoOutput.Output parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static guru.bonacci.reactive.kafka.ProtoOutput.Output parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static guru.bonacci.reactive.kafka.ProtoOutput.Output parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static guru.bonacci.reactive.kafka.ProtoOutput.Output parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static guru.bonacci.reactive.kafka.ProtoOutput.Output parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static guru.bonacci.reactive.kafka.ProtoOutput.Output parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(guru.bonacci.reactive.kafka.ProtoOutput.Output prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Output}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Output)
        guru.bonacci.reactive.kafka.ProtoOutput.OutputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return guru.bonacci.reactive.kafka.ProtoOutput.internal_static_protobuf_Output_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return guru.bonacci.reactive.kafka.ProtoOutput.internal_static_protobuf_Output_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                guru.bonacci.reactive.kafka.ProtoOutput.Output.class, guru.bonacci.reactive.kafka.ProtoOutput.Output.Builder.class);
      }

      // Construct using guru.bonacci.reactive.kafka.ProtoOutput.Output.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        foo_ = "";
        goo_ = 0;
        bar_ = 0D;
        baz_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return guru.bonacci.reactive.kafka.ProtoOutput.internal_static_protobuf_Output_descriptor;
      }

      @java.lang.Override
      public guru.bonacci.reactive.kafka.ProtoOutput.Output getDefaultInstanceForType() {
        return guru.bonacci.reactive.kafka.ProtoOutput.Output.getDefaultInstance();
      }

      @java.lang.Override
      public guru.bonacci.reactive.kafka.ProtoOutput.Output build() {
        guru.bonacci.reactive.kafka.ProtoOutput.Output result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public guru.bonacci.reactive.kafka.ProtoOutput.Output buildPartial() {
        guru.bonacci.reactive.kafka.ProtoOutput.Output result = new guru.bonacci.reactive.kafka.ProtoOutput.Output(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(guru.bonacci.reactive.kafka.ProtoOutput.Output result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.foo_ = foo_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.goo_ = goo_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.bar_ = bar_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.baz_ = baz_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof guru.bonacci.reactive.kafka.ProtoOutput.Output) {
          return mergeFrom((guru.bonacci.reactive.kafka.ProtoOutput.Output)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(guru.bonacci.reactive.kafka.ProtoOutput.Output other) {
        if (other == guru.bonacci.reactive.kafka.ProtoOutput.Output.getDefaultInstance()) return this;
        if (other.hasId()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasFoo()) {
          foo_ = other.foo_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasGoo()) {
          setGoo(other.getGoo());
        }
        if (other.hasBar()) {
          setBar(other.getBar());
        }
        if (other.hasBaz()) {
          setBaz(other.getBaz());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasFoo()) {
          return false;
        }
        if (!hasGoo()) {
          return false;
        }
        if (!hasBar()) {
          return false;
        }
        if (!hasBaz()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                foo_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                goo_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 33: {
                bar_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 40: {
                baz_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       * @return Whether the id field is set.
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object foo_ = "";
      /**
       * <code>required string foo = 2;</code>
       * @return Whether the foo field is set.
       */
      public boolean hasFoo() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string foo = 2;</code>
       * @return The foo.
       */
      public java.lang.String getFoo() {
        java.lang.Object ref = foo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            foo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string foo = 2;</code>
       * @return The bytes for foo.
       */
      public com.google.protobuf.ByteString
          getFooBytes() {
        java.lang.Object ref = foo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          foo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string foo = 2;</code>
       * @param value The foo to set.
       * @return This builder for chaining.
       */
      public Builder setFoo(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        foo_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required string foo = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFoo() {
        foo_ = getDefaultInstance().getFoo();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>required string foo = 2;</code>
       * @param value The bytes for foo to set.
       * @return This builder for chaining.
       */
      public Builder setFooBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        foo_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int goo_ ;
      /**
       * <code>required int32 goo = 3;</code>
       * @return Whether the goo field is set.
       */
      @java.lang.Override
      public boolean hasGoo() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int32 goo = 3;</code>
       * @return The goo.
       */
      @java.lang.Override
      public int getGoo() {
        return goo_;
      }
      /**
       * <code>required int32 goo = 3;</code>
       * @param value The goo to set.
       * @return This builder for chaining.
       */
      public Builder setGoo(int value) {

        goo_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 goo = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGoo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        goo_ = 0;
        onChanged();
        return this;
      }

      private double bar_ ;
      /**
       * <code>required double bar = 4;</code>
       * @return Whether the bar field is set.
       */
      @java.lang.Override
      public boolean hasBar() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required double bar = 4;</code>
       * @return The bar.
       */
      @java.lang.Override
      public double getBar() {
        return bar_;
      }
      /**
       * <code>required double bar = 4;</code>
       * @param value The bar to set.
       * @return This builder for chaining.
       */
      public Builder setBar(double value) {

        bar_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>required double bar = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBar() {
        bitField0_ = (bitField0_ & ~0x00000008);
        bar_ = 0D;
        onChanged();
        return this;
      }

      private boolean baz_ ;
      /**
       * <code>required bool baz = 5;</code>
       * @return Whether the baz field is set.
       */
      @java.lang.Override
      public boolean hasBaz() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required bool baz = 5;</code>
       * @return The baz.
       */
      @java.lang.Override
      public boolean getBaz() {
        return baz_;
      }
      /**
       * <code>required bool baz = 5;</code>
       * @param value The baz to set.
       * @return This builder for chaining.
       */
      public Builder setBaz(boolean value) {

        baz_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>required bool baz = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBaz() {
        bitField0_ = (bitField0_ & ~0x00000010);
        baz_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Output)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Output)
    private static final guru.bonacci.reactive.kafka.ProtoOutput.Output DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new guru.bonacci.reactive.kafka.ProtoOutput.Output();
    }

    public static guru.bonacci.reactive.kafka.ProtoOutput.Output getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Output>
        PARSER = new com.google.protobuf.AbstractParser<Output>() {
      @java.lang.Override
      public Output parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Output> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Output> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public guru.bonacci.reactive.kafka.ProtoOutput.Output getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Output_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Output_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014output.proto\022\010protobuf\"H\n\006Output\022\n\n\002id" +
      "\030\001 \002(\t\022\013\n\003foo\030\002 \002(\t\022\013\n\003goo\030\003 \002(\005\022\013\n\003bar\030" +
      "\004 \002(\001\022\013\n\003baz\030\005 \002(\010B*\n\033guru.bonacci.react" +
      "ive.kafkaB\013ProtoOutput"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_Output_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Output_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Output_descriptor,
        new java.lang.String[] { "Id", "Foo", "Goo", "Bar", "Baz", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
